@ct-api
@auth-server
Feature: Contagion

  @cleanRules
  @cleanEstablishments
  @cleanOwners
  @cleanUsers
  @cleanVisits
  @cleanBillboard
  Scenario: User gets classified as high risk
    Given the owner with email "owner_e2e_33@gmail.com" and password "owner33" was created
    And the establishment called "wunderbar2" has characteristics:
      | type    | restaurant          |
      | name    | Wunderbar           |
      | address | Cabildo 1010        |
      | city    | CABA                |
      | state   | CABA                |
      | zip     | 1430ACV             |
      | country | Argentina           |
    And "wunderbar2" has a space with characteristics:
      | name                   | Primer piso |
      | hasExit                | true        |
      | m2                     | 10          |
      | estimatedVisitDuration | 60          |
      | openPlace              | false       |
      | n95Mandatory           | false       |
    And the owner with email "owner_e2e_33@gmail.com" owns the establishment "wunderbar2"
    And the user with email "testing40@gmail.com", DNI "40404040" and password "pass1234" was created
    And the user log in with email "testing40@gmail.com" and password "pass1234"
    And we generate a genux token for "testing40@gmail.com"
    And the user with email "testing41@gmail.com", DNI "40404040" and password "pass1234" was created
    And the user log in with email "testing41@gmail.com" and password "pass1234"
    And we generate a genux token for "testing41@gmail.com"
    When the establishment "wunderbar2" is created
    And the user with email "testing40@gmail.com" visited the space from establishment "wunderbar2" 180 minutes ago with user data:
      | vaccinated             | 1           |
      | covidRecovered         | true        |
      | vaccinatedDate         | 01/01/2021  |
      | covidRecoveredDate     | 01/05/2021  |
      | vacccineReceived       | AstraZeneca |
    And the user with email "testing41@gmail.com" visited the space from establishment "wunderbar2" 175 minutes ago with user data:
      | vaccinated             | 0           |
      | covidRecovered         | false       |
    And the admin logs in
    And a new rule identified by the name "rule1" is created with fields:
      | index                     | 1                  |
      | contagionRisk             | Alto               |
      | m2Cmp                     | <                  |
      | m2Value                   | 30                 |
    And we generate a genux token for "testing40@gmail.com"
    And the user with email "testing40@gmail.com" exposes their codes as infected
    And we wait until the contagion updater runs
    And the user "testing41@gmail.com" gets the billboard of compromised codes
    Then the status code for the visit creation of the user with email "testing40@gmail.com" is 201
    And the status code for the visit creation of the user with email "testing41@gmail.com" is 201
    And the status code for the rule "rule1" creation is 201
    And the status code for the visit exposure of the user with email "testing40@gmail.com" is 201
    And the code generated by the user with email "testing41@gmail.com" is in the billboard
