const { Given, When, Then } = require('cucumber');
const assert = require('assert');
const chai = require('chai')
const got = require('got');
const expect = chai.expect
chai.use(require('chai-as-promised'))

When('the user with email {string} visited the space from establishment {string} {int} minutes ago with user data:', async function (email, establishment_name, minutes, dataTable) {
  this.visits[email] = {};
  try {
    const userGeneratedCode = `userGeneratedCode${(new Date()).toISOString()}`;
    const scanCode = this.establishments[establishment_name]['res']['body']['spaces'][0];
    const entranceTimestamp = new Date();
    entranceTimestamp.setMinutes(entranceTimestamp.getMinutes() - minutes);
    const req_body = {
      userGeneratedCode,
      scanCode,
      entranceTimestamp,
      ...buildVisitInformation(dataTable.rowsHash())
    };
    const headers = buildHeaders(this.users[email]['generateGenuxToken']['res']['body']['genuxToken']);
    const res = await this.http.post('visits', {
      json: req_body,
      headers,
      responseType: 'json'
    });
    this.visits[email]['_id'] = res.body._id;
    this.visits[email]['req_body'] = req_body;
    this.visits[email]['status_code'] = res.statusCode;
    this.visits[email]['creation_success'] = res.statusCode === 201;
    this.visits[email]['res'] = res;
    this.visits[email]['userGeneratedCode'] = userGeneratedCode;
  } catch (err) {
    this.visits[email]['err'] = err;
    this.visits[email]['creation_success'] = false;
    this.visits[email]['status_code'] = 401;
  }
});

When('the user with email {string} closed the visit to the space from establishment {string} {int} minutes ago with user data:', async function (email, establishment_name, minutes, dataTable) {
  this.visits[email] = this.visits[email] || {};
  this.visits[email]['exit'] = {};
  try {
    const userGeneratedCode = this.visits[email]['userGeneratedCode'];
    const scanCode = this.establishments[establishment_name]['res']['body']['spaces'][0];
    const exitTimestamp = new Date();
    exitTimestamp.setMinutes(exitTimestamp.getMinutes() - minutes);
    const req_body = {
      userGeneratedCode,
      scanCode,
      exitTimestamp,
      ...buildVisitInformation(dataTable.rowsHash())
    };
    const headers = buildHeaders(this.users[email]['generateGenuxToken']['res']['body']['genuxToken']);
    const res = await this.http.post('visits/addExitTimestamp', {
      json: req_body,
      headers,
      responseType: 'json'
    });
    this.visits[email]['exit']['_id'] = res.body._id;
    this.visits[email]['exit']['status_code'] = res.statusCode;
    this.visits[email]['exit']['exit_success'] = res.statusCode === 201;
    this.visits[email]['exit']['res'] = res;
  } catch (err) {
    this.visits[email]['exit']['err'] = err;
    this.visits[email]['exit']['exit_success'] = false;
    this.visits[email]['exit']['status_code'] = 401;
  }
});

When('the user with email {string} exposes their codes as infected', async function (email) {
  this.visits[email] = this.visits[email] || {};
  this.visits[email]['infected'] = {};
  try {
    const headers = buildHeaders(this.users[email]['generateGenuxToken']['res']['body']['genuxToken']);
    const res = await this.http.post('infected', {
      json: this.visits[email]['req_body'],
      headers,
      responseType: 'json'
    });
    this.visits[email]['infected']['_id'] = res.body._id;
    this.visits[email]['infected']['status_code'] = res.statusCode;
    this.visits[email]['infected']['creation_success'] = res.statusCode === 201;
    this.visits[email]['infected']['res'] = res;
  } catch (err) {
    this.visits[email]['infected']['err'] = err;
    this.visits[email]['infected']['creation_success'] = false;
    this.visits[email]['infected']['status_code'] = 401;
  }
});

When('we wait until the contagion updater runs', async function () {
  await new Promise(r => setTimeout(r, 5000));
});

When('the user {string} gets the billboard of compromised codes', async function (email) {
  const headers = buildHeadersAccessToken(this.users[email]['logIn']['res'].body.accessToken);
  const res = await this.http.get("billboard", {
      headers,
      responseType: 'json'
    });
  this.billboard = res.body;
});

Then('the status code for the visit creation of the user with email {string} is {int}', function (email, statusCode) {
  assert.strictEqual(this.visits[email]['status_code'], statusCode);
});

Then('the status code for the visit exit of the user with email {string} is {int}', function (email, statusCode) {
  assert.strictEqual(this.visits[email]['exit']['status_code'], statusCode);
});

Then('the status code for the visit exposure of the user with email {string} is {int}', function (email, statusCode) {
  assert.strictEqual(this.visits[email]['infected']['status_code'], statusCode);
});

Then('the code generated by the user with email {string} is in the billboard with risk {string}', function (email, risk) {
  const codes = this.billboard.map(x => x['userGeneratedCode']);
  expect(codes).to.include(this.visits[email]['userGeneratedCode']);
  const visit = this.billboard.filter(x => x['userGeneratedCode'] === this.visits[email]['userGeneratedCode']);
  assert.strictEqual(visit[0]['risk'], RiskStringToSeverity[risk]);
});

const buildHeaders = (genuxToken) => {
  return {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'genux-token': genuxToken,
    'json': true
  };
}

const buildHeadersAccessToken = (accessToken) => {
  return {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'access-token': accessToken,
    'json': true
  };
}

const buildVisitInformation = (dataTable) => {
  typedDataTable = {};
  for (const [key, value] of Object.entries(dataTable)) {
    typedDataTable[key] = correctTypeFromKey(key, value);
  }
  return typedDataTable;
}

const correctTypeFromKey = (key, value) => {
  if (['vaccinated'].includes(key)) {
    return parseInt(value);
  }
  if (['covidRecovered'].includes(key)) {
    return value === 'true';
  }
  if (['vaccinatedDate', 'covidRecoveredDate'].includes(key)) {
    return new Date(value);
  }
  return value;
}

const RiskStringToSeverity = {
  'Alto': 0,
  'Medio': 1,
  'Bajo': 2,
};
